server:
  port: 6868
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: study-eureka
